# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=32)),
                ('status', models.CharField(default='Closed', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=polls.models.upload_location)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FightPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('status', models.CharField(default='Closed', max_length=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='polls.Fighter')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
                ('red_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='polls.Fighter')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='PerformancePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('status', models.CharField(default='Closed', max_length=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Fighter')),
            ],
        ),
        migrations.AddField(
            model_name='fightpoll',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Match'),
        ),
    ]
