# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_fighter_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='fightpoll',
            name='event',
        ),
        migrations.RemoveField(
            model_name='fightpoll',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FightPoll',
        ),
    ]
