# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160621_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='poll_status',
        ),
        migrations.RemoveField(
            model_name='performancepoll',
            name='status',
        ),
    ]
