# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160621_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='votes',
        ),
    ]
