# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_match_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancepoll',
            name='event',
        ),
        migrations.RemoveField(
            model_name='performancepoll',
            name='fighter',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.AddField(
            model_name='fighter',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PerformancePoll',
        ),
    ]
