# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160621_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 19, 38, 17, 783946, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
