# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='polls.Event'),
            preserve_default=False,
        ),
    ]
