# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_fighter_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Event'),
        ),
    ]
